services:
  auth-service:
    build: ./auth-service
    container_name: auth-service
    ports:
      - "8001:8000"
    env_file:
      - ./auth-service/.env
    command: uvicorn main:app --host 0.0.0.0 --port 8000
    working_dir: /app
    volumes:
      - ./auth-service:/app

  account-service:
    build: ./account-service
    container_name: account-service
    ports:
      - "8002:8000"
    env_file:
      - ./account-service/.env
    command: uvicorn main:app --host 0.0.0.0 --port 8000
    working_dir: /app
    volumes:
      - ./account-service:/app